# FROM node:20-alpine

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# COPY . .

# EXPOSE 3000

# CMD ["npm", "run", "dev"]
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --prefer-offline --fetch-retry-mintimeout 20000 --fetch-retry-maxtimeout 120000 --fetch-retries 5

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
